package skyrimalchemylab

class AlchemyService {

    void insertEffects(){
        def builder = new Runnable(){
            @Delegate EffectBuilder eb = new EffectBuilder()

            void run() {
                effect("Anfälligkeit für Blitz", '-')
                effect("Anfälligkeit für Feuer", '-')
                effect("Anfälligkeit für Frost", '-')
                effect("Anfälligkeit für Gift", '-')
                effect("Anfälligkeit für Magie", '-')
                effect("Ausdauer regenerieren", '+')
                effect("Ausdauer senken", '-')
                effect("Ausdauer verstärken", '+')
                effect("Ausdauer wiederherstellen", '+')
                effect("Ausdauerregeneration senken", '-')
                effect("Beschwörung verstärken", '+')
                effect("Blitzresistenz", '+')
                effect("Blocken verstärken", '+')
                effect("Dauerhafter Ausdauerschaden", '-')
                effect("Dauerhafter Magickaschaden", '-')
                effect("Dauerhafter Gesundheitsschaden", '-')
                effect("Einhändig verstärken", '+')
                effect("Erzürnen", '-')
                effect("Feuerresistenz", '+')
                effect("Frostresistenz", '+')
                effect("Furcht", '-')
                effect("Gesundheit regenerieren", '+')
                effect("Gesundheit senken", '-')
                effect("Gesundheit verstärken", '+')
                effect("Gesundheit wiederherstellen", '+')
                effect("Giftresistenz", '+')
                effect("Illusion verstärken", '+')
                effect("Krankheit heilen", '+')
                effect("Lähmen", '-')
                effect("Leichte Rüstung verstärken", '+')
                effect("Magicka regenerieren", '+')
                effect("Magicka senken", '-')
                effect("Magicka verstärken", '+')
                effect("Magicka wiederherstellen", '+')
                effect("Magickaregeneration senken", '-')
                effect("Magieresistenz", '+')
                effect("Raserei", '-')
                effect("Redekunst verstärken", '+')
                effect("Schleichen verstärken", '+')
                effect("Schloßknacken verstärken", '+')
                effect("Schmiedekunst verstärken", '+')
                effect("Schwere Rüstung verstärken", '+')
                effect("Taschendiebstahl verstärken", '+')
                effect("Tragfähigkeit verstärken", '+')
                effect("Unsichtbarkeit", '+')
                effect("Veränderung verstärken", '+')
                effect("Verlangsamen", '-')
                effect("Verzaubern verstärken", '+')
                effect("Wasseratmung", '+')
                effect("Wiederherstellung verstärken", '+')
                effect("Zerstörung verstärken", '+')
                effect("Zielkunst verstärken", '+')
                effect("Zweihändig verstärken", '+')

                withEffects {ef -> ef.save()}
                log.debug("inserted effects")
            }
        }
        builder.run()
    }

    void insertEffectAliases(){
        EffectBuilder eb = new EffectBuilder(Language.findByIsoCode("en"))
        eb.alias("Weakness to Shock","Anfälligkeit für Blitz")
        eb.alias("Weakness to Fire","Anfälligkeit für Feuer")
        eb.alias("Weakness to Frost","Anfälligkeit für Frost")
        eb.alias("Weakness to Poison","Anfälligkeit für Gift")
        eb.alias("Weakness to Magicka","Anfälligkeit für Magie")
        eb.alias("Regenerate Stamina","Ausdauer regenerieren")
        eb.alias("Damage Stamina","Ausdauer senken")
        eb.alias("Fortify Stamina","Ausdauer verstärken")
        eb.alias("Restore Stamina","Ausdauer wiederherstellen")
        eb.alias("Damage Stamina Regen","Ausdauerregeneration senken")
        eb.alias("Fortify Conjuration","Beschwörung verstärken")
        eb.alias("Resist Shock","Blitzresistenz")
        eb.alias("Fortify Block","Blocken verstärken")
        eb.alias("Ravage Stamina","Dauerhafter Ausdauerschaden")
        eb.alias("Ravage Health","Dauerhafter Gesundheitsschaden")
        eb.alias("Ravage Magicka","Dauerhafter Magickaschaden")
        eb.alias("Fortify One-handed","Einhändig verstärken")
        eb.alias("Frenzy","Erzürnen")
        eb.alias("Resist Fire","Feuerresistenz")
        eb.alias("Resist Frost","Frostresistenz")
        eb.alias("Fear","Furcht")
        eb.alias("Regenerate Health","Gesundheit regenerieren")
        eb.alias("Damage Health","Gesundheit senken")
        eb.alias("Fortify Health","Gesundheit verstärken")
        eb.alias("Restore Health","Gesundheit wiederherstellen")
        eb.alias("Resist Poison","Giftresistenz")
        eb.alias("Fortify Illusion","Illusion verstärken")
        eb.alias("Cure Diseas","Krankheit heilen")
        eb.alias("Fortify Light Armor","Leichte Rüstung verstärken")
        eb.alias("Paralysis","Lähmen")
        eb.alias("Regenerate Magicka","Magicka regenerieren")
        eb.alias("Damage Magicka","Magicka senken")
        eb.alias("Fortify Magicka","Magicka verstärken")
        eb.alias("Restore Magicka","Magicka wiederherstellen")
        eb.alias("Damage Magicka Regen","Magickaregeneration senken")
        eb.alias("Resist Magic","Magieresistenz")
        eb.alias("Fury","Raserei")
        eb.alias("Fortify Barter","Redekunst verstärken")
        eb.alias("Fortify Sneak","Schleichen verstärken")
        eb.alias("Fortify Lockpicking","Schloßknacken verstärken")
        eb.alias("Fortify Smithing","Schmiedekunst verstärken")
        eb.alias("Fortify Heavy Armor","Schwere Rüstung verstärken")
        eb.alias("Fortify Pickpocket","Taschendiebstahl verstärken")
        eb.alias("Fortify Carry Weight","Tragfähigkeit verstärken")
        eb.alias("Invisibility","Unsichtbarkeit")
        eb.alias("Slow","Verlangsamen")
        eb.alias("Fortify Enchanting","Verzaubern verstärken")
        eb.alias("Fortify Alteration","Veränderung verstärken")
        eb.alias("Waterbreathing","Wasseratmung")
        eb.alias("Fortify Restoration","Wiederherstellung verstärken")
        eb.alias("Fortify Destruction","Zerstörung verstärken")
        eb.alias("Fortify Archery","Zielkunst verstärken")
        eb.alias("Fortify Two-handed","Zweihändig verstärken")

        eb.withEffects {ef -> ef.save()}
        log.debug("inserted effect aliases")
    }

    
    void insertIngredients(){
        def builder = new Runnable(){
            @Delegate IngredientBuilder ib = new IngredientBuilder();

            void run() {
                ingredient(name:"Abeceanischer Mirakelbarsch", price:15, weight:0.5, source:"Flüsse", effects:["Wiederherstellung verstärken","Anfälligkeit für Frost","Anfälligkeit für Gift","Schleichen verstärken"])
                ingredient(name:"Bärenklaue", price:2, weight:0.1, source:"Wildnis", effects:["Ausdauer wiederherstellen","Gesundheit verstärken","Einhändig verstärken","Magickaregeneration senken"])
                ingredient(name:"Berits Asche", price:5, weight:0.2, source:"", effects:["Ausdauer senken","Feuerresistenz","Beschwörung verstärken","Dauerhafter Ausdauerschaden"])
                ingredient(name:"Biene", price:3, weight:0.1, source:"Bienenstock", effects:["Anfälligkeit für Blitz","Ausdauer regenerieren","Ausdauer senken","Ausdauer wiederherstellen"])
                ingredient(name:"Bienenstockhülle", price:5, weight:1.0, source:"Bienenstock", effects:["Giftresistenz","Leichte Rüstung verstärken","Schleichen verstärken","Zerstörung verstärken"])
                ingredient(name:"Blasenpilz", price:12, weight:0.2, source:"Höhlen", effects:["Ausdauer senken","Gesundheit wiederherstellen","Erzürnen","Schmiedekunst verstärken"])
                ingredient(name:"Blaue Bergblume", price:2, weight:0.1, source:"Steppenlandschaft", effects:["Beschwörung verstärken","Gesundheit wiederherstellen","Gesundheit verstärken","Magickaregeneration senken"])
                ingredient(name:"Blaue Pfeilfedern", price:1, weight:0.1, source:"Libellen", effects:["Blitzresistenz","Taschendiebstahl verstärken","Gesundheit wiederherstellen","Furcht"])
                ingredient(name:"Blauer Schmetterlingsflügel", price:2, weight:0.1, source:"Blauer Schmetterling", effects:["Verzaubern verstärken","Beschwörung verstärken","Ausdauer senken","Magickaregeneration senken"])
                ingredient(name:"Blutende Krone", price:10, weight:0.3, source:"Höhlen", effects:["Anfälligkeit für Feuer","Blocken verstärken","Magieresistenz","Anfälligkeit für Gift"])
                ingredient(name:"Caniswurzel", price:5, weight:0.1, source:"Klippen/Felsen", effects:["Ausdauer senken","Zielkunst verstärken","Einhändig verstärken","Lähmen"])
                ingredient(name:"Chauruseier", price:10, weight:0.2, source:"Schwarzweite", effects:["Anfälligkeit für Gift","Magicka senken","Unsichtbarkeit","Ausdauer verstärken"])
                ingredient(name:"Cyrodilischer Spatenschwanz", price:15, weight:0.3, source:"Flüsse", effects:["Ausdauer senken","Wiederherstellung verstärken","Furcht","Gesundheit senken"])
                ingredient(name:"Daedraherz", price:250, weight:0.5, source:"Daedra", effects:["Gesundheit wiederherstellen","Magicka senken","Ausdauerregeneration senken","Furcht"])
                ingredient(name:"Distelzweig", price:1, weight:0.1, source:"Steppenlandschaft", effects:["Ausdauer senken","Frostresistenz","Giftresistenz","Schwere Rüstung verstärken"])
                ingredient(name:"Dornenherz", price:20, weight:0.5, source:"Büsche", effects:["Magicka wiederherstellen","Blocken verstärken","Lähmen","Magicka verstärken"])
                ingredient(name:"Drachenbaum", price:5, weight:0.1, source:"Vulkanische Tundra", effects:["Zweihändig verstärken","Feuerresistenz","Redekunst verstärken","Illusion verstärken"])
                ingredient(name:"Drosselei", price:2, weight:0.5, source:"Vogelnester", effects:["Anfälligkeit für Gift","Ausdauer wiederherstellen","Schloßknacken verstärken","Blitzresistenz"])
                ingredient(name:"Eisgeistzähne", price:30, weight:0.3, source:"Eisgeister", effects:["Anfälligkeit für Feuer","Unsichtbarkeit","Schwere Rüstung verstärken","Anfälligkeit für Frost"])
                ingredient(name:"Eismirriam", price:1, weight:0.1, source:"", effects:["Frostresistenz","Magicka senken","Schleichen verstärken","Ausdauerregeneration senken"])
                ingredient(name:"Ektoplasma", price:25, weight:0.1, source:"Geisterwesen", effects:["Magicka wiederherstellen","Magicka verstärken","Zerstörung verstärken","Gesundheit senken"])
                ingredient(name:"Elfenohr", price:10, weight:0.1, source:"", effects:["Magicka wiederherstellen","Zielkunst verstärken","Anfälligkeit für Frost","Feuerresistenz"])
                ingredient(name:"Fackelwürmchenbrust", price:1, weight:0.1, source:"", effects:["Anfälligkeit für Magie","Ausdauer verstärken","Ausdauer wiederherstellen","Dauerhafter Magickaschaden"])
                ingredient(name:"Falkenfedern", price:15, weight:0.1, source:"", effects:["Krankheit heilen","Leichte Rüstung verstärken","Einhändig verstärken","Schleichen verstärken"])
                ingredient(name:"Falkenschnabel", price:15, weight:0.25, source:"", effects:["Tragfähigkeit verstärken","Blitzresistenz","Frostresistenz","Ausdauer wiederherstellen"])
                ingredient(name:"Falmerohr", price:10, weight:0.2, source:"Falmer", effects:["Gesundheit senken","Erzürnen","Giftresistenz","Schloßknacken verstärken"])
                ingredient(name:"Feuersalze", price:50, weight:0.3, source:"Feueratronach", effects:["Feuerresistenz","Magicka wiederherstellen","Anfälligkeit für Frost","Magicka regenerieren"])
                ingredient(name:"Flusspeitscher", price:15, weight:0.25, source:"", effects:["Gesundheit senken","Verlangsamen","Tragfähigkeit verstärken","Veränderung verstärken"])
                ingredient(name:"Frostsalze", price:100, weight:0.3, source:"Frostatronach", effects:["Anfälligkeit für Feuer","Frostresistenz","Magicka wiederherstellen","Beschwörung verstärken"])
                ingredient(name:"Glühstaub", price:20, weight:0.5, source:"Irrlichtmutter", effects:["Magicka senken","Magickaregeneration senken","Zerstörung verstärken","Blitzresistenz"])
                ingredient(name:"Grassamen", price:1, weight:0.1, source:"", effects:["Giftresistenz","Magicka senken","Veränderung verstärken","Magicka wiederherstellen"])
                ingredient(name:"Großes Geweih", price:2, weight:0.1, source:"Elche", effects:["Ausdauer wiederherstellen","Ausdauer verstärken","Verlangsamen","Ausdauerregeneration senken"])
                ingredient(name:"Hängemoos", price:1, weight:0.3, source:"Ruinen/Felsen", effects:["Magicka senken","Gesundheit verstärken","Magickaregeneration senken","Einhändig verstärken"])
                ingredient(name:"Hexenrabenfedern", price:20, weight:0.1, source:"Hexenraben", effects:["Erzürnen","Magicka senken","Beschwörung verstärken","Anfälligkeit für Blitz"])
                ingredient(name:"Hexenrabenklaue", price:20, weight:0.3, source:"Hexenraben", effects:["Magieresistenz","Dauerhafter Magickaschaden","Verzaubern verstärken","Redekunst verstärken"])
                ingredient(name:"Histkarpfen", price:6, weight:0.3, source:"Flüsse", effects:["Ausdauer wiederherstellen","Magicka verstärken","Ausdauerregeneration senken","Wasseratmung"])
                ingredient(name:"Honigwabe", price:5, weight:1.0, source:"Bienenstock", effects:["Blocken verstärken","Ausdauer senken","Leichte Rüstung verstärken","Ausdauer wiederherstellen"])
                ingredient(name:"Hühnerei", price:2, weight:0.5, source:"Hühnernester", effects:["Magieresistenz","Magickaregeneration senken","Wasseratmung","Dauerhafter Ausdauerschaden"])
                ingredient(name:"Jarrinwurzel", price:10, weight:0.5, source:"", effects:["Gesundheit senken","Magickaregeneration senken","Magicka senken","Ausdauer senken"])
                ingredient(name:"Jasbaytrauben", price:1, weight:0.2, source:"Vulkanische Tundra", effects:["Magicka senken","Anfälligkeit für Magie","Magicka verstärken","Gesundheit senken"])
                ingredient(name:"Kleine Perle", price:2, weight:0.1, source:"", effects:["Frostresistenz","Einhändig verstärken","Wiederherstellung verstärken","Ausdauer wiederherstellen"])
                ingredient(name:"Kleines Geweih", price:2, weight:0.1, source:"", effects:["Anfälligkeit für Gift","Wiederherstellung verstärken","Dauerhafter Ausdauerschaden","Gesundheit senken"])
                ingredient(name:"Knoblauch", price:1, weight:0.3, source:"", effects:["Ausdauer verstärken","Gesundheit regenerieren","Giftresistenz","Magicka regenerieren"])
                ingredient(name:"Knochenmehl", price:5, weight:0.5, source:"Skelette/Draugr", effects:["Ausdauer senken","Dauerhafter Ausdauerschaden","Beschwörung verstärken","Feuerresistenz"])
                ingredient(name:"Koboldschemel", price:0, weight:0.3, source:"Höhlen", effects:["Gesundheit senken","Dauerhafter Gesundheitsschaden","Lähmen","Gesundheit wiederherstellen"])
                ingredient(name:"Kriechranke", price:1, weight:0.2, source:"Vulkanische Tundra", effects:["Magicka wiederherstellen","Ausdauerregeneration senken","Gesundheit verstärken","Anfälligkeit für Magie"])
                ingredient(name:"Lavendel", price:1, weight:0.1, source:"Lavendelpflanze", effects:["Ausdauer verstärken","Beschwörung verstärken","Magicka senken","Magieresistenz"])
                ingredient(name:"Magisches Leichentuch", price:2, weight:0.1, source:"Irrlichtmutter", effects:["Ausdauer wiederherstellen","Zerstörung verstärken","Gesundheit verstärken","Magieresistenz"])
                ingredient(name:"Menschenfleisch", price:1, weight:0.3, source:"", effects:["Gesundheit senken","Lähmen","Magicka wiederherstellen","Schleichen verstärken"])
                ingredient(name:"Menschliches Herz", price:1, weight:0.25, source:"", effects:["Magickaregeneration senken","Magicka senken","Raserei","Gesundheit senken"])
                ingredient(name:"Mondfalterflügel", price:5, weight:0.1, source:"Mondfalter", effects:["Magicka senken","Leichte Rüstung verstärken","Gesundheit regenerieren","Unsichtbarkeit"])
                ingredient(name:"Mondzucker", price:50, weight:0.25, source:"", effects:["Anfälligkeit für Feuer","Frostresistenz","Magicka wiederherstellen","Magicka regenerieren"])
                ingredient(name:"Mora Tapinella", price:4, weight:0.3, source:"Tote Bäume", effects:["Magicka wiederherstellen","Gesundheit senken","Ausdauer regenerieren","Illusion verstärken"])
                ingredient(name:"Namiras Fäulnis", price:0, weight:0.3, source:"Höhlen", effects:["Magicka senken","Schloßknacken verstärken","Furcht","Gesundheit regenerieren"])
                ingredient(name:"Nirnwurz", price:10, weight:0.2, source:"Gewässer", effects:["Gesundheit senken","Ausdauer senken","Unsichtbarkeit","Magieresistenz"])
                ingredient(name:"Nordranke", price:5, weight:0.2, source:"Unterwasser", effects:["Magicka senken","Wasseratmung","Gesundheit regenerieren","Taschendiebstahl verstärken"])
                ingredient(name:"Orangene Pfeilfedern", price:1, weight:0.1, source:"Libellen", effects:["Ausdauer wiederherstellen","Magicka senken","Taschendiebstahl verstärken","Gesundheit senken"])
                ingredient(name:"Perle", price:2, weight:0.1, source:"", effects:["Ausdauer wiederherstellen","Blocken verstärken","Blitzresistenz","Magicka wiederherstellen"])
                ingredient(name:"Pfahlwurzel", price:15, weight:0.5, source:"Zweiglinge", effects:["Anfälligkeit für Magie","Illusion verstärken","Magicka regenerieren","Magicka wiederherstellen"])
                ingredient(name:"Pulverisierter Mammutstoßzahn", price:2, weight:0.1, source:"Mammuts", effects:["Ausdauer wiederherstellen","Schleichen verstärken","Anfälligkeit für Feuer","Furcht"])
                ingredient(name:"Purpurne Nirnwurz", price:10, weight:0.2, source:"Schwarzweite", effects:["Magieresistenz","Unsichtbarkeit","Gesundheit senken","Ausdauer senken"])
                ingredient(name:"Rauer Wulstling", price:2, weight:0.1, source:"Höhlen", effects:["Feuerresistenz","Zweihändig verstärken","Raserei","Ausdauer regenerieren"])
                ingredient(name:"Riesenflechte", price:5, weight:0.25, source:"", effects:["Anfälligkeit für Blitz","Gesundheit senken","Anfälligkeit für Gift","Magicka wiederherstellen"])
                ingredient(name:"Riesenzeh", price:20, weight:1.0, source:"Riesen", effects:["Ausdauer senken","Gesundheit verstärken","Tragfähigkeit verstärken","Ausdauerregeneration senken"])
                ingredient(name:"Rote Bergblume", price:2, weight:0.1, source:"Steppenlandschaft", effects:["Magicka wiederherstellen","Magicka senken","Magicka verstärken","Gesundheit senken"])
                ingredient(name:"Säbelzahntigerauge", price:2, weight:0.1, source:"Säbelzahntiger", effects:["Ausdauer wiederherstellen","Gesundheit wiederherstellen","Gesundheit senken","Magicka senken"])
                ingredient(name:"Säbelzahntigerreißzahn", price:2, weight:0.1, source:"Säbelzahntiger", effects:["Ausdauer wiederherstellen","Schwere Rüstung verstärken","Schmiedekunst verstärken","Anfälligkeit für Gift"])
                ingredient(name:"Salz", price:2, weight:0.2, source:"Fässer", effects:["Wiederherstellung verstärken","Magicka regenerieren","Verlangsamen","Anfälligkeit für Magie"])
                ingredient(name:"Salze der Leere", price:125, weight:0.2, source:"Sturmatronach", effects:["Anfälligkeit für Blitz","Magieresistenz","Gesundheit senken","Magicka verstärken"])
                ingredient(name:"Schimmerpilz", price:5, weight:0.2, source:"Höhlen", effects:["Blitzresistenz","Zerstörung verstärken","Schmiedekunst verstärken","Gesundheit verstärken"])
                ingredient(name:"Schlachterfischei", price:3, weight:0.2, source:"Unterwasser", effects:["Giftresistenz","Taschendiebstahl verstärken","Gesundheit senken","Ausdauer verstärken"])
                ingredient(name:"Schlachterfischschuppen", price:3, weight:0.1, source:"Schlachterfisch", effects:["Gesundheit senken","Schwere Rüstung verstärken","Dauerhafter Gesundheitsschaden","Frostresistenz"])
                ingredient(name:"Schlammkrabben Chitin", price:2, weight:0.3, source:"Schlammkrabben", effects:["Ausdauer wiederherstellen","Krankheit heilen","Giftresistenz","Feuerresistenz"])
                ingredient(name:"Schmetterlingsflügel", price:3, weight:0.1, source:"Landschaften", effects:["Gesundheit wiederherstellen","Redekunst verstärken","Dauerhafter Ausdauerschaden","Magicka senken"])
                ingredient(name:"Schneebeeren", price:4, weight:0.1, source:"Schneelandschaften", effects:["Feuerresistenz","Frostresistenz","Blitzresistenz","Verzaubern verstärken"])
                ingredient(name:"Schuppenschwamm", price:4, weight:0.3, source:"Morsche Birken", effects:["Anfälligkeit für Magie","Illusion verstärken","Ausdauer regenerieren","Tragfähigkeit verstärken"])
                ingredient(name:"Silberbarsch", price:15, weight:0.3, source:"Gewässer", effects:["Ausdauer wiederherstellen","Gesundheit senken","Frostresistenz","Ausdauerregeneration senken"])
                ingredient(name:"Skeeverschwanz", price:3, weight:0.2, source:"Skeever", effects:["Ausdauerregeneration senken","Dauerhafter Gesundheitsschaden","Gesundheit senken","Leichte Rüstung verstärken"])
                ingredient(name:"Spinnenei", price:5, weight:0.2, source:"Spinnennester", effects:["Ausdauer senken","Magickaregeneration senken","Schloßknacken verstärken","Zielkunst verstärken"])
                ingredient(name:"Steinhuscherei", price:2, weight:0.5, source:"Nester", effects:["Gesundheit wiederherstellen","Einhändig verstärken","Ausdauer senken","Anfälligkeit für Magie"])
                ingredient(name:"Sumpfpilzschote", price:3, weight:0.5, source:"Sumpf von Morthal", effects:["Blitzresistenz","Dauerhafter Magickaschaden","Lähmen","Gesundheit wiederherstellen"])
                ingredient(name:"Todesglockenblume", price:4, weight:0.1, source:"Mortal, gefrorene Tundra", effects:["Gesundheit senken","Ausdauer senken","Verlangsamen","Anfälligkeit für Gift"])
                ingredient(name:"Tollkirsche", price:8, weight:0.1, source:"Friedhöfe", effects:["Gesundheit senken","Magickaregeneration senken","Dauerhafter Ausdauerschaden","Zerstörung verstärken"])
                ingredient(name:"Trollfett", price:15, weight:1.0, source:"Trolle", effects:["Giftresistenz","Zweihändig verstärken","Erzürnen","Gesundheit senken"])
                ingredient(name:"Tundrabaumwolle", price:1, weight:0.1, source:"Siehe Name", effects:["Magieresistenz","Blocken verstärken","Magicka verstärken","Redekunst verstärken"])
                ingredient(name:"Vampirstaub", price:25, weight:0.2, source:"Vampire, Silber Hand", effects:["Unsichtbarkeit","Magicka wiederherstellen","Gesundheit regenerieren","Krankheit heilen"])
                ingredient(name:"Verkohltes Skeeverfell", price:1, weight:0.5, source:"Kochstellen", effects:["Ausdauer wiederherstellen","Krankheit heilen","Giftresistenz","Gesundheit wiederherstellen"])
                ingredient(name:"Violette Bergblume", price:2, weight:0.1, source:"Steppenlandschaft", effects:["Ausdauer wiederherstellen","Schleichen verstärken","Dauerhafter Magickaschaden","Frostresistenz"])
                ingredient(name:"Wacholderbeeren", price:1, weight:0.1, source:"Wacholderbusch", effects:["Anfälligkeit für Feuer","Ausdauerregeneration senken","Zielkunst verstärken","Gesundheit regenerieren"])
                ingredient(name:"Weißkappe", price:0, weight:0.3, source:"Weißkappenpilze", effects:["Anfälligkeit für Frost","Magicka wiederherstellen","Schwere Rüstung verstärken","Magicka senken"])
                ingredient(name:"Weizen", price:5, weight:0.1, source:"Farmen, Kisten, Verkauf", effects:["Ausdauerregeneration senken","Gesundheit wiederherstellen","Gesundheit verstärken","Dauerhafter Magickaschaden"])
                ingredient(name:"Zweiglingsaft", price:5, weight:0.2, source:"Zweiglinge", effects:["Magickaregeneration senken","Verzaubern verstärken","Schmiedekunst verstärken","Veränderung verstärken"])
                ingredient(name:"Zwergenöl", price:15, weight:0.3, source:"Zwergenruinen", effects:["Anfälligkeit für Magie","Illusion verstärken","Magicka regenerieren","Magicka wiederherstellen"])

                withIngredients {ing -> ing.save()}
                log.debug("inserted ingredients")
            }
        }
        builder.run()
    }

    void insertIngredientAliases(){
        IngredientBuilder ib = new IngredientBuilder(Language.findByIsoCode("en"))
        ib.alias("Abecean Longfin","Abeceanischer Mirakelbarsch")
        ib.alias("Bear Claws","Bärenklaue")
        ib.alias("Berit's Ashes","Berits Asche")
        ib.alias("Bee","Biene")
        ib.alias("Beehive Husk","Bienenstockhülle")
        ib.alias("Blisterwort","Blasenpilz")
        ib.alias("Blue Mountain Flower","Blaue Bergblume")
        ib.alias("Blue Dartwing","Blaue Pfeilfedern")
        ib.alias("Blue Butterfly Wing","Blauer Schmetterlingsflügel")
        ib.alias("Bleeding Crown","Blutende Krone")
        ib.alias("Canis Root","Caniswurzel")
        ib.alias("Chaurus Eggs","Chauruseier")
        ib.alias("Cyrodilic Spadetail","Cyrodilischer Spatenschwanz")
        ib.alias("Daedra Heart","Daedraherz")
        ib.alias("Thistle Branch","Distelzweig")
        ib.alias("Briar Heart","Dornenherz")
        ib.alias("Dragon's Tongue","Drachenbaum")
        ib.alias("Pine Thrush Egg","Drosselei")
        ib.alias("Ice Wraith Teeth","Eisgeistzähne")
        ib.alias("Frost Mirriam","Eismirriam")
        ib.alias("Ectoplasm","Ektoplasma")
        ib.alias("Elves Ear","Elfenohr")
        ib.alias("Torchbug Thorax","Fackelwürmchenbrust")
        ib.alias("Hawk Feathers","Falkenfedern")
        ib.alias("Hawk Beak","Falkenschnabel")
        ib.alias("Falmer Ear","Falmerohr")
        ib.alias("Fire Salts","Feuersalze")
        ib.alias("River Betty","Flusspeitscher")
        ib.alias("Frost Salts","Frostsalze")
        ib.alias("Glow Dust","Glühstaub")
        ib.alias("Grass Pod","Grassamen")
        ib.alias("Large Antlers","Großes Geweih")
        ib.alias("Hanging Moss","Hängemoos")
        ib.alias("Hagraven Feathers","Hexenrabenfedern")
        ib.alias("Hagraven Claw","Hexenrabenklaue")
        ib.alias("Histcarp","Histkarpfen")
        ib.alias("Honeycomb","Honigwabe")
        ib.alias("Chicken's Egg","Hühnerei")
        ib.alias("Jarrin Root","Jarrinwurzel")
        ib.alias("Jazbay Grapes","Jasbaytrauben")
        ib.alias("Small Pearl","Kleine Perle")
        ib.alias("Small Antlers","Kleines Geweih")
        ib.alias("Garlic","Knoblauch")
        ib.alias("Bone Meal","Knochenmehl")
        ib.alias("Imp Stool","Koboldschemel")
        ib.alias("Creep Cluster","Kriechranke")
        ib.alias("Lavender","Lavendel")
        ib.alias("Wisp Wrappings","Magisches Leichentuch")
        ib.alias("Human Flesh","Menschenfleisch")
        ib.alias("Human Heart","Menschliches Herz")
        ib.alias("Luna Moth Wing","Mondfalterflügel")
        ib.alias("Moon Sugar","Mondzucker")
        ib.alias("Mora Tapinella","Mora Tapinella")
        ib.alias("Namira's Rot","Namiras Fäulnis")
        ib.alias("Nirnroot","Nirnwurz")
        ib.alias("Nordic Barnacle","Nordranke")
        ib.alias("Orange Dartwing","Orangene Pfeilfedern")
        ib.alias("Pearl","Perle")
        ib.alias("Taproot","Pfahlwurzel")
        ib.alias("Powdered Mammoth Tusk","Pulverisierter Mammutstoßzahn")
        ib.alias("Crimson Nirnroot","Purpurne Nirnwurz")
        ib.alias("Fly Amanita","Rauer Wulstling")
        ib.alias("Giant Lichen","Riesenflechte")
        ib.alias("Giant's Toe","Riesenzeh")
        ib.alias("Red Mountain Flower","Rote Bergblume")
        ib.alias("Eye of Sabre Cat","Säbelzahntigerauge")
        ib.alias("Sabre Cat Tooth","Säbelzahntigerreißzahn")
        ib.alias("Salt Pile","Salz")
        ib.alias("Void Salts","Salze der Leere")
        ib.alias("Glowing Mushroom","Schimmerpilz")
        ib.alias("Slaughterfish Egg","Schlachterfischei")
        ib.alias("Slaughterfish Scales","Schlachterfischschuppen")
        ib.alias("Mudcrab Chitin","Schlammkrabben Chitin")
        ib.alias("Butterfly Wing","Schmetterlingsflügel")
        ib.alias("Snowberries","Schneebeeren")
        ib.alias("Scaly Pholiota","Schuppenschwamm")
        ib.alias("Silverside Perch","Silberbarsch")
        ib.alias("Skeever Tail","Skeeverschwanz")
        ib.alias("Spider Egg","Spinnenei")
        ib.alias("Rock Warbler Egg","Steinhuscherei")
        ib.alias("Swamp Fungal Pod","Sumpfpilzschote")
        ib.alias("Deathbell","Todesglockenblume")
        ib.alias("Nightshade","Tollkirsche")
        ib.alias("Troll Fat","Trollfett")
        ib.alias("Tundra Cotton","Tundrabaumwolle")
        ib.alias("Vampire Dust","Vampirstaub")
        ib.alias("Charred Skeever Hide","Verkohltes Skeeverfell")
        ib.alias("Purple Mountain Flower","Violette Bergblume")
        ib.alias("Juniper Berries","Wacholderbeeren")
        ib.alias("White Cap","Weißkappe")
        ib.alias("Wheat","Weizen")
        ib.alias("Spriggan Sap","Zweiglingsaft")
        ib.alias("Dwarven Oil","Zwergenöl")

        ib.withIngredients {ing -> ing.save()}
        log.debug("inserted ingredient aliases")
    }
}
